all: 
	javac -cp ../../lib/servlet-api.jar:WEB-INF/lib/sqlite-jdbc-3.32.3.2.jar:WEB-INF/lib/antlr-4.9-complete.jar:WEB-INF/lib/antlr-4.9-complete.jar WEB-INF/src/ejemplo/*.java -d WEB-INF/classes
	../../bin/catalina.sh run